


```{r}
install.packages("pacman")

pacman::p_load(jsonlite, tidyverse, lubridate)

source("SMK_dataframe.R")
```

```{r}
golden_paintings <- fromJSON("https://api.smk.dk/api/v1/art/search/?keys=*&range=[production_dates_start%3A{1800-01-01T00%3A00%3A00.000Z%3B1849-12-31T00%3A00%3A00.000Z}]&filters=[has_image:true],[object_names:maleri],[public_domain:true]&offset=0&rows=2000")

golden_paintings$items -> golden_paintings

```

```{r}
golden_paintings %>% 
  head()
```

```{r}
SMK_dataframe(golden_paintings) -> golden_paintings
```


```{r}
golden_paintings %>% 
  head()
```

```{r}
golden_paintings %>% 
  count(creator_1, sort = TRUE)
```

```{r}
golden_paintings %>% 
  select(exhibitions, title, creator_1)
```

```{r}
# 7 is the row number, exhibitions is the 17th column and [[1]] is for diving into the data frame
golden_paintings[7, 17][[1]]
```

```{r}
golden_paintings %>% 
  unnest(exhibitions) %>% 
  select(exhibition, everything()) -> golden_paintings_exh

golden_paintings_exh
```

```{r}
golden_paintings_exh %>% 
  count(title, creator_1, frontend_url, sort = TRUE)
```

```{r}
golden_paintings_exh %>% 
  count(title, creator_1, frontend_url, sort = TRUE) %>% 
  slice_max(n, n = 5) %>%
  mutate(title = reorder(title, n)) %>% 
  ggplot(aes(x = title, y = n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
      labs(x = "Title of art piece",
      y = "Count",
      title = "Count of times an art piece\nhas been on exhibition") + 
  theme(axis.text.y = element_text(angle = 14, hjust = 1))
```

## Acquisition Analysis

```{r}
golden_paintings %>% 
  mutate(year = year(acquisition_date_precision)) %>%
  count(year) %>% 
  ggplot(aes(year, n)) +
  geom_col()
```

```{r}
golden_paintings %>% 
  mutate(year = year(acquisition_date_precision)) %>%
  count(year, creator_1_gender) %>% 
  ggplot(aes(year, n)) +
  geom_col(aes(fill = creator_1_gender))
```

## Extracting Colors and Comparison

```{r, message=FALSE}
pacman::p_load(imager)
```




